const SUCCESS_STATUS = 200
const DEFAULT_STATUS = 400
const NOT_FOUND_STATUS = 404
const ERROR_STATUS = 500
const AUTH_FAILED_STATUS = 503
const TOKEN_HASH_KEY = 'W2s78r9fdsf7qsEdq74d979e86zuo3ii2r23uo3u89e798r7'
const SALT_ROUNDS_BCRYPT = 9

module.exports = {
  SUCCESS_STATUS,
  DEFAULT_STATUS,
  NOT_FOUND_STATUS,
  ERROR_STATUS,
  AUTH_FAILED_STATUS,
  TOKEN_HASH_KEY,
  SALT_ROUNDS_BCRYPT
}
